# Generated by Django 6.0 on 2025-12-25 15:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('servie', 'Servie'), ('payee', 'Payée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_service', models.DateTimeField(blank=True, null=True, verbose_name='Date de service')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='tables.tablerestaurant', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commandes',
                'ordering': ['-date_commande'],
                'permissions': [('can_view_all_orders', 'Peut voir toutes les commandes'), ('can_serve_order', 'Peut marquer une commande comme servie'), ('can_pay_order', 'Peut enregistrer un paiement')],
            },
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.commande', verbose_name='Commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande_items', to='menu.plat', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'db_table': 'commande_items',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='tables.tablerestaurant', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'db_table': 'paniers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message="La quantité doit être d'au moins 1"), django.core.validators.MaxValueValidator(10, message='La quantité ne peut pas dépasser 10')], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.panier', verbose_name='Panier')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panier_items', to='menu.plat', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'db_table': 'panier_items',
                'unique_together': {('panier', 'plat')},
            },
        ),
    ]
