# Generated by Django 6.0 on 2026-01-11 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_panier_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='caissier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_caissier', to=settings.AUTH_USER_MODEL, verbose_name='Caissier (a encaissé)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_serveur', to=settings.AUTH_USER_MODEL, verbose_name='Serveur (a commandé)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validateur (a servi)'),
        ),
    ]
