# Generated by Django 6.0 on 2026-01-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='categorie',
            field=models.CharField(blank=True, default='Général', max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='plat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
