# Generated by Django 6.0 on 2026-01-03

from django.db import migrations, models


CATEGORIES = ['Poulet', 'Jus', 'Viande', 'Poisson', 'Chawarma']


def normalize_categories(apps, schema_editor):
    Plat = apps.get_model('menu', 'Plat')

    # Valeurs vides ou anciennes valeurs -> Poulet
    Plat.objects.filter(categorie__isnull=True).update(categorie='Poulet')
    Plat.objects.filter(categorie__exact='').update(categorie='Poulet')
    Plat.objects.filter(categorie='Général').update(categorie='Poulet')

    # Toute valeur non prévue -> Poulet
    Plat.objects.exclude(categorie__in=CATEGORIES).update(categorie='Poulet')


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_plat_categorie_plat_description'),
    ]

    operations = [
        migrations.RunPython(normalize_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.CharField(
                choices=[
                    ('Poulet', 'Poulet'),
                    ('Jus', 'Jus'),
                    ('Viande', 'Viande'),
                    ('Poisson', 'Poisson'),
                    ('Chawarma', 'Chawarma'),
                ],
                default='Poulet',
                max_length=100,
                verbose_name='Catégorie',
            ),
        ),
    ]
