# Generated by Django 6.0 on 2026-01-03

from django.db import migrations, models


DEFAULT_CATEGORIES = ['Poulet', 'Jus', 'Viande', 'Poisson', 'Chawarma']


def seed_categories(apps, schema_editor):
    CategoriePlat = apps.get_model('menu', 'CategoriePlat')
    Plat = apps.get_model('menu', 'Plat')

    # Créer les catégories par défaut (ordre stable)
    for i, nom in enumerate(DEFAULT_CATEGORIES):
        CategoriePlat.objects.get_or_create(nom=nom, defaults={'ordre': i})

    # Ajouter automatiquement les anciennes catégories existantes dans les plats
    # (utile si des données ont été saisies avant)
    existing = set(CategoriePlat.objects.values_list('nom', flat=True))
    extra = (
        Plat.objects.exclude(categorie__isnull=True)
        .exclude(categorie__exact='')
        .values_list('categorie', flat=True)
        .distinct()
    )
    ordre = CategoriePlat.objects.aggregate(m=models.Max('ordre')).get('m')
    ordre = 0 if ordre is None else ordre + 1
    for nom in extra:
        if nom not in existing:
            CategoriePlat.objects.create(nom=nom, ordre=ordre)
            ordre += 1


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_plat_categorie_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories_plats',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.CharField(default='Poulet', max_length=100, verbose_name='Catégorie'),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
