# Generated by Django 4.2.27 on 2026-02-04 14:51

# Final migration to mark current state as synchronized
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20260204_1450'),
    ]

    operations = [
        # Migration vide - le modèle est déjà synchronisé avec la base de données
        migrations.RunSQL(
            sql="SELECT 1",  # SQL neutre
            reverse_sql="SELECT 1"
        ),
    ]
