# Generated by Django 4.2.27 on 2026-02-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_final_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='categorie_fk',
        ),
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.categorieplat', verbose_name='Catégorie'),
        ),
    ]
