# Generated by Django 6.0 on 2025-12-25 15:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('date_depense', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/depenses/%Y/%m/%d/', verbose_name='Justificatif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='payments.caisse', verbose_name='Caisse')),
                ('type_depense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='payments.typedepense', verbose_name='Type de dépense')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to=settings.AUTH_USER_MODEL, verbose_name='Enregistrée par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'depenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
