# Generated by Django 6.0 on 2025-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='est_valide',
            field=models.BooleanField(default=False, help_text='Cocher pour confirmer que le paiement a bien été effectué.', verbose_name='Paiement validé ?'),
        ),
    ]
