# Generated by Django 6.0 on 2026-01-03

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_tablerestaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerestaurant',
            name='nombre_clients_actuels',
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Nombre de clients',
            ),
        ),
    ]
