# Generated by Django 6.0 on 2025-12-25 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de dépense',
                'verbose_name_plural': 'Types de dépense',
                'db_table': 'types_depense',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Solde initial de la caisse')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Solde actuel de la caisse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('notes_fermeture', models.TextField(blank=True, verbose_name='Notes de clôture')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture de la caisse")),
                ('date_fermeture', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture de la caisse')),
                ('est_ouverte', models.BooleanField(default=True, verbose_name='Caisse ouverte ?')),
                ('utilisateur_fermeture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caisses_fermees', to=settings.AUTH_USER_MODEL, verbose_name='Fermée par')),
                ('utilisateur_ouverture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caisses_ouvertes', to=settings.AUTH_USER_MODEL, verbose_name='Ouverte par')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'db_table': 'caisse',
                'permissions': [('can_open_register', 'Peut ouvrir la caisse'), ('can_close_register', 'Peut fermer la caisse'), ('can_view_register', 'Peut voir les détails de la caisse')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant payé')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('cheque', 'Chèque'), ('autre', 'Autre')], max_length=10, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence (numéro de chèque, etc.)')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='payments.caisse', verbose_name='Caisse')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='orders.commande', verbose_name='Commande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Encaissé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
                'permissions': [('can_register_payment', 'Peut enregistrer un paiement'), ('can_view_payment', 'Peut voir les détails des paiements')],
            },
        ),
        migrations.CreateModel(
            name='SortieCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, verbose_name='Date de la sortie')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la sortie')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/depenses/%Y/%m/%d/', verbose_name='Justificatif (facultatif)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties', to='payments.caisse', verbose_name='Caisse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Effectuée par')),
                ('type_depense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties', to='payments.typedepense', verbose_name='Type de dépense')),
            ],
            options={
                'verbose_name': 'Sortie de caisse',
                'verbose_name_plural': 'Sorties de caisse',
                'db_table': 'sorties_caisse',
                'ordering': ['-date_sortie'],
                'permissions': [('can_register_expense', 'Peut enregistrer une dépense'), ('can_view_expense', 'Peut voir les détails des dépenses')],
            },
        ),
    ]
