# Generated by Django 6.0 on 2025-12-25 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.CharField(max_length=50, unique=True, verbose_name='Numéro de table')),
                ('nombre_places', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places')),
                ('current_status', models.CharField(choices=[('libre', 'Libre'), ('commande_en_attente', 'Commande en attente'), ('commande_servie', 'Commande servie'), ('commande_payee', 'Commande payée')], default='libre', max_length=30, verbose_name='Statut actuel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'tables_restaurant',
                'ordering': ['numero_table'],
            },
        ),
    ]
