# Generated by Django 6.0 on 2026-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Rtable', 'Table'), ('Rservent', 'Serveur/Servante'), ('Rcuisinier', 'Cuisinier'), ('Rcaissier', 'Caissier'), ('Rcomptable', 'Comptable'), ('Radmin', 'Administrateur')], max_length=20),
        ),
    ]
